### ISSUE TITLE
Service - ToDo

### ISSUE THREAD

**Issue by JesperPetersenDk** [JesperPetersenDk/BlazorToDo#9]
- [x] Oprettelse af Services
- [x] Tilføj information til list
- [x] Oprettelse af form
- [x] Fremvisning af information fra listen.
- [x] Positive tests: Test at servicemetoder returnerer forventede resultater under normale forhold.
- [x] Negative tests: Test hvordan din service håndterer fejl, f.eks. når input er ugyldigt eller når en undtagelse kastes.
